version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: auto-libs
    versions:
    - 0.3.29
    - 0.3.30
    - 0.3.34
    - 0.3.36
    - 0.3.37
    - 0.3.38
  - dependency-name: "@umijs/test"
    versions:
    - 3.3.10
    - 3.3.11
    - 3.3.7
    - 3.3.8
    - 3.3.9
    - 3.4.0
    - 3.4.11
    - 3.4.2
    - 3.4.4
    - 3.4.5
    - 3.4.6
    - 3.4.7
    - 3.4.8
  - dependency-name: "@umijs/preset-react"
    versions:
    - 1.7.13
    - 1.8.0
    - 1.8.1
    - 1.8.2
    - 1.8.3
    - 1.8.4
    - 1.8.6
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: dumi
    versions:
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
    - 1.1.7
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: less
    versions:
    - 4.1.0
